services:
  db:
    image: mysql:8.0
    container_name: mysql_biblioteca
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: bash -c "docker-php-ext-install mysqli pdo_mysql && apache2-foreground"

  web:
    image: php:8.2-apache
    container_name: php_apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
